### 查询服务
GET http://127.0.0.1:9001/imooc/commerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcIkltb29jUWlueWlAaW1vb2MuY29tXCJ9IiwianRpIjoiODY3YmYwMjUtOWVlZi00MmFkLWIwOGMtMTY4OWUyM2FiNmMxIiwiZXhwIjoxNjYxNzAyNDAwfQ.EmFD81Hiy26-F1h0twVNLsftEkc_aZcLOjxPtx2AAzjuBrRRVkkYiTpJYUY2J32A9ypURzcChLZmaD4kpLShWJowh2C0BO_9zWyAmODMXusZExiCHq4uBebzBYsI_RsAKQcDKehZ_caEN6S_fjzYPENX8ArScshsd6gM_4nq09AzZd4dJJiQxUMk1btFEfxCTgkvRk_w3ZMlRCLjrAmG0mS3_U0NSKNQaixUbYe5-FmQVlTiNsLeNms-nFkJkBTYYD_Ey5Mp_Qyi7mjWtHOo6Fwc_azpAkiIEtrPPVqVz6UsWGoIDmojQ_AYq7xbOJi6Vhdeq-JsM3kDk1RWjpCeFQ
token: imooc
